[package]
name = "commputer-storage"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Blockchain state storage: blocks, accounts, proofs"

[dependencies]
commputer-core = { workspace = true }
serde = { workspace = true }
borsh = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
sha2 = { workspace = true }
serde_json = { workspace = true }
hex = "0.4"
rocksdb = { workspace = true }
ed25519-dalek = { workspace = true }

[dev-dependencies]
tempfile = "3"
