[package]
name = "commputer-network"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "P2P networking: gossip for consensus, DHT for data routing"

[dependencies]
commputer-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
borsh = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
hex = "0.4"
libp2p = { workspace = true }
